# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        MMC\User\Bundle\LoginBundle\Entity\LoginFormAuthenticator: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        mmc_user_provider:
            entity: { class: MMC\User\Bundle\UserBundle\Entity\User }
        mmc_login_provider:
            entity: { class: MMC\User\Bundle\LoginBundle\Entity\LoginFormAuthenticator, property: login }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            guard:
                authenticators:
                    - mmc_user.component.security.login_form_authenticator
            logout:
                path: /logout

            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds

            oauth:
                resource_owners:
                    trello: "/login/check-trello"
                oauth_user_provider:
                    service: mmc_ro_user_provider
                failure_path: /login
                login_path: /login


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }