services:

    mmc_user.component.security.token_generator:
        class: MMC\User\Component\Security\TokenGenerator

    mmc_user.component.controller.security:
        class: MMC\User\Bundle\UserBundle\Controller\SecurityController
        arguments:
            - '@router'
            - '@templating'
            - '@security.authentication_utils'
            - '@form.factory'

    mmc_user.component.routing.extra_loader.registration:
        class: MMC\User\Component\Routing\ExtraLoader
        arguments:
            - '%mmc_user.routing.routeName.registration%'
            - '%mmc_user.routing.pattern.registration%'
            - '%mmc_user.routing.controllerAction.registration%'
            - '%mmc_login.registration.condition%'
        tags:
            - { name: routing.loader }

    mmc_user.chain.authenticator_block:
        class: MMC\User\Bundle\UserBundle\Services\AuthenticatorBlock\ChainAuthenticatorBlock

parameters:

    mmc_user.routing.routeName.registration: 'mmc_user.registration'
    mmc_user.routing.pattern.registration: '/register'
    mmc_user.routing.controllerAction.registration: 'mmc_user.component.controller.registration:registerAction'
