services:

    #CONTROLLER
    mmc_user.component.controller.security:
        class: MMC\User\Component\Controller\SecurityController
        arguments:
            - '@router'
            - '@templating'
            - '@security.authentication_utils'
            - '@form.factory'

    mmc_user.component.security.login_form_authenticator:
        class: MMC\User\Component\Security\LoginFormAuthenticator
        arguments:
            - '@form.factory'
            - '@mmc_user.repository.login_form_authenticator'
            - '@router'
            - '@security.user_password_encoder.generic'

    mmc_user.repository.login_form_authenticator:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - MMC\User\Bundle\UserBundle\Entity\LoginFormAuthenticator

    mmc_user.component.security.has_password_listener:
        class: MMC\User\Component\Doctrine\HashPasswordListener
        arguments:
            - '@security.user_password_encoder.generic'
        tags:
            - { name: doctrine.event_subscriber }
