mmc_user.registration_confirmation:
    path:     /confirm/{token}
    defaults: { _controller: mmc_user.component.controller.registration:confirmAction }

mmc_user.forgot_password:
    path:     /forgot_password
    defaults: { _controller: mmc_user.component.controller.resetting:forgotPasswordAction }

mmc_user.resetting:
    path:     /resetting/{token}
    defaults: { _controller: mmc_user.component.controller.resetting:resettingAction }

mmc_user.email_form.code:
    path:     /email_code
    defaults: { _controller: mmc_user.email_form.controller:sendCodeAction }

mmc_user.email_form:
    path:     /email_check
    defaults: { _controller: mmc_user.component.controller.security:loginAction }

mmc_user.email_form.registration:
    path:     /registration/email
    defaults: { _controller: mmc_user.email_form.controller:registrationAction }
